name: FE Docker CI Prod

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js (for PNPM)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS Account ID
        id: aws-account
        run: echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Docker Image Tag
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          IMAGE="$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/youtil/fe-prod"
          echo "IMAGE_TAG=${IMAGE}:${TIMESTAMP}" >> $GITHUB_ENV
          echo "IMAGE_LATEST=${IMAGE}:latest" >> $GITHUB_ENV

      - name: Create .env.production file
        run: echo "${{ secrets.ENV_PROD }}" > .env

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_TAG }} -t ${{ env.IMAGE_LATEST }} .

      - name: Push Docker Images
        run: |
          docker push ${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_LATEST }}
      - name: Trigger ArgoCD by updating values.yaml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${{ secrets.CLOUD_REPO_TOKEN }}@github.com/100-hours-a-week/1-team-YouTIL-cloud.git
          cd 1-team-YouTIL-cloud
          
          echo "# updated at $(date +%Y-%m-%dT%H:%M:%S)" >> v2/helm/youtil-fe/values.yaml

          git add v2/helm/youtil-fe/values.yaml
          git commit -m "ğŸ” FE Docker image updated: Trigger ArgoCD"
          git push origin main

